insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('1', 'Sebastian', 'Ziolkowski', 'Kardiologia', '1991-01-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('2', 'Jan', 'Stepien', 'Audiologia i foniatria', '2000-08-30', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('3', 'Slawomir', 'Nowakowski', 'Zdrowie Publiczne', '1990-07-03', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('4', 'Jadwiga', 'Jankowska', 'Patomorfologia', '2000-05-04', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('5', 'Anna', 'Dudek', 'Urologia', '1995-10-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('6', 'Mateusz', 'Ostrowski', 'Pediatria', '1995-06-21', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('7', 'Dariusz', 'Witkowski', 'Chirurgia ogolna', '1996-06-06', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('8', 'Joanna', 'Wilk', 'Psychiatria dzieci i mlodziezy', '1997-12-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('9', 'Karol', 'Majewski', 'Radioterapia onkologiczna', '1992-03-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('10', 'Roman', 'Dudek', 'Audiologia i foniatria', '1996-01-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('11', 'Dariusz', 'Ziolkowski', 'Choroby wewnetrzne', '1990-12-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('12', 'Przemyslaw', 'Majewski', 'Diagnostyka laboratoryjna', '1998-04-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('13', 'Karolina', 'Szymczak', 'Dermatologia i wenerologia', '1993-01-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('14', 'Mateusz', 'Wysocki', 'Psychiatria dzieci i mlodziezy', '2000-12-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('15', 'Sebastian', 'Wisniewski', 'Psychiatria dzieci i mlodziezy', '1999-01-25', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('16', 'Teresa', 'Mazurek', 'Chirurgia ogolna', '1992-11-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('17', 'Edyta', 'Mazurek', 'Mikrobiologia lekarska', '1997-07-07', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('18', 'Jadwiga', 'Kaminska', 'Dermatologia i wenerologia', '1991-02-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('19', 'Sylwia', 'Kucharska', 'Medycyna ratunkowa', '2000-12-11', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('20', 'Adam', 'Kubiak', 'Psychiatria', '1991-03-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('21', 'Janusz', 'Wisniewski', 'Dermatologia i wenerologia', '1992-10-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('22', 'Jadwiga', 'Glowacka', 'Neonatologia', '1997-03-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('23', 'Grazyna', 'Tomaszewska', 'Onkologia kliniczna', '1997-03-03', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('24', 'Jacek', 'Kozlowski', 'Okulistyka', '1994-12-28', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('25', 'Henryk', 'Dudek', 'Radiologia i diagnostyka obrazowa', '1997-10-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('26', 'Jan', 'Sikorski', 'Otorynolaryngologia', '1991-07-11', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('27', 'Sebastian', 'Nowakowski', 'Radioterapia onkologiczna', '1990-01-25', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('28', 'Stanislawa', 'Baranowska', 'Onkologia kliniczna', '1991-03-28', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('29', 'Katarzyna', 'Szymczak', 'Onkologia kliniczna', '1996-11-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('30', 'Monika', 'Kucharska', 'Patomorfologia', '1999-03-25', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('31', 'Mateusz', 'Baranowski', 'Patomorfologia', '1991-06-12', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('32', 'Marek', 'Przybylski', 'Urologia', '1996-03-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('33', 'Bozena', 'Wozniak', 'Anestezjologia i intensywna terapia', '1994-04-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('34', 'Aleksandra', 'Kalinowska', 'Medycyna transportu', '1996-12-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('35', 'Daniel', 'Krol', 'Kardiochirurgia', '1998-03-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('36', 'Slawomir', 'Andrzejewski', 'Anestezjologia i intensywna terapia', '1994-02-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('37', 'Anna', 'Krawczyk', 'Psychiatria', '1994-08-20', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('38', 'Danuta', 'Maciejewska', 'Radioterapia onkologiczna', '1992-10-26', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('39', 'Jacek', 'Kozlowski', 'Neonatologia', '1995-06-02', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('40', 'Genowefa', 'Majewska', 'Epidemiologia', '1990-07-18', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('41', 'Mariusz', 'Marciniak', 'Audiologia i foniatria', '1999-02-15', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('42', 'Wojciech', 'Rutkowski', 'Radiologia i diagnostyka obrazowa', '1997-07-14', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('43', 'Stefania', 'Zajac', 'Pediatria', '1998-12-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('44', 'Przemyslaw', 'Gorski', 'Chirurgia ogolna', '2000-05-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('45', 'Jaroslaw', 'Zielinski', 'Psychiatria dzieci i mlodziezy', '1996-08-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('46', 'Janina', 'Lewandowska', 'Urologia', '2000-09-07', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('47', 'Aleksandra', 'Wroblewska', 'Chirurgia szczekowo-twarzowa', '1990-05-08', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('48', 'Anna', 'Nowakowska', 'Chirurgia plastyczna', '1998-06-28', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('49', 'Dorota', 'Bak', 'Otorynolaryngologia', '1998-08-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('50', 'Henryk', 'Sawicki', 'Otorynolaryngologia', '1993-06-26', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('51', 'Ewelina', 'Dabrowska', 'Mikrobiologia lekarska', '1998-01-04', 'null')
