insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('1', 'Renata', 'Jankowska', 'Medycyna pracy', '1995-10-19', '1998-06-14');
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('2', 'Patrycja', 'Dabrowska', 'Poloznictwo i ginekologia', '1993-12-16', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('3', 'Janina', 'Wisniewska', 'Medycyna pracy', '1999-01-11', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('4', 'Genowefa', 'Ostrowska', 'Medycyna ratunkowa', '1998-02-26', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('5', 'Grazyna', 'Jankowska', 'Medycyna transportu', '1998-01-02', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('6', 'Piotr', 'Gorski', 'Medycyna ratunkowa', '1992-08-28', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('7', 'Leszek', 'Baranowski', 'Urologia', '1991-03-26', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('8', 'Grazyna', 'Michalak', 'Psychiatria', '1990-11-29', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('9', 'Patrycja', 'Ostrowska', 'Rehabilitacja medyczna', '1994-08-01', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('10', 'Ewa', 'Nowakowska', 'Patomorfologia', '1999-12-25', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('11', 'Tadeusz', 'Wilk', 'Audiologia i foniatria', '1991-10-03', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('12', 'Andrzej', 'Witkowski', 'Mikrobiologia lekarska', '1991-11-06', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('13', 'Kazimierz', 'Wieczorek', 'Pediatria', '1993-01-30', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('14', 'Daniel', 'Michalak', 'Pediatria', '1995-09-10', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('15', 'Natalia', 'Walczak', 'Psychiatria', '1999-09-14', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('16', 'Agnieszka', 'Nowak', 'Medycyna nuklearna', '1995-04-22', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('17', 'Czeslaw', 'Czarnecki', 'Kardiochirurgia', '2000-03-23', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('18', 'Iwona', 'Grabowska', 'Medycyna ratunkowa', '1994-03-07', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('19', 'Aleksandra', 'Wilk', 'Otorynolaryngologia', '2000-08-04', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('20', 'Mateusz', 'Stepien', 'Urologia', '1990-11-29', '2000-12-09');
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('21', 'Lukasz', 'Ziolkowski', 'Urologia', '1995-01-31', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('22', 'Przemyslaw', 'Chmielewski', 'Chirurgia plastyczna', '2000-05-24', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('23', 'Mariusz', 'Michalak', 'Chirurgia szczekowo-twarzowa', '1994-06-12', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('24', 'Artur', 'Bak', 'Medycyna transportu', '1991-02-02', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('25', 'Danuta', 'Kolodziej', 'Medycyna transportu', '1994-06-26', null);
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data_zatrudnienia", "Data_zwolnienia") values ('26', 'Natalia', 'Jablonska', 'Kardiologia', '1999-08-27', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('1', 'Kazimiera', 'Marciniak', '1995-11-24', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('2', 'Agata', 'Kaczmarek', '1997-07-04', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('3', 'Danuta', 'Baranowska', '1992-03-28', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('4', 'Genowefa', 'Michalska', '1991-01-06', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('5', 'Halina', 'Makowska', '1999-11-13', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('6', 'Danuta', 'Maciejewska', '1993-11-28', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('7', 'Irena', 'Sokolowska', '1999-04-04', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('8', 'Genowefa', 'Sikora', '1998-11-07', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('9', 'Bozena', 'Kaminska', '1991-07-25', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('10', 'Renata', 'Michalska', '1994-07-05', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('11', 'Agata', 'Jakubowska', '1990-03-25', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('12', 'Sylwia', 'Nowicka', '1990-01-06', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('13', 'Maria', 'Wroblewska', '2000-11-02', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('14', 'Teresa', 'Kwiatkowska', '1995-07-13', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('15', 'Agnieszka', 'Michalska', '1997-12-24', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('16', 'Patrycja', 'Witkowska', '1991-11-27', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('17', 'Natalia', 'Kowalska', '1996-05-03', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('18', 'Maria', 'Laskowska', '1994-12-03', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('19', 'Aleksandra', 'Wrobel', '1992-12-01', '1999-09-23');
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('20', 'Agnieszka', 'Krawczyk', '1993-04-18', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('21', 'Justyna', 'Michalska', '1995-01-21', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('22', 'Stanislawa', 'Zakrzewska', '1993-07-19', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('23', 'Urszula', 'Zajac', '1991-07-23', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('24', 'Iwona', 'Pawlowska', '1994-06-09', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('25', 'Iwona', 'Wisniewska', '1999-11-29', null);
insert into Pielegniarka ("ID", "Imie", "Nazwisko", "Data zatrudnienia", "Data zwolnienia") values ('26', 'Elzbieta', 'Ziolkowska', '2000-01-09', null);
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('36050696173', 'Krystyna', 'Wojciechowska', '1936-05-06');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('07102582372', 'Jerzy', 'Duda', '1907-10-25');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('98033127985', 'Slawomir', 'Duda', '1998-03-31');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('79061310141', 'Krzysztof', 'Ziolkowski', '1979-06-13');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('06101291052', 'Renata', 'Bak', '1906-10-12');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('97042255430', 'Kazimiera', 'Wojcik', '1997-04-22');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('01081386371', 'Beata', 'Andrzejewska', '1901-08-13');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('73012758111', 'Marian', 'Borkowski', '1973-01-27');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('32032726668', 'Leszek', 'Adamski', '1932-03-27');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('37092170188', 'Urszula', 'Brzezinska', '1937-09-21');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('55021696928', 'Janusz', 'Przybylski', '1955-02-16');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('19062316521', 'Monika', 'Glowacka', '1919-06-23');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('04011387894', 'Aleksandra', 'Pawlowska', '1904-01-13');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('83030898247', 'Grazyna', 'Wojcik', '1983-03-08');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('08060429910', 'Beata', 'Dabrowska', '1908-06-04');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('75110916195', 'Marcin', 'Szczepanski', '1975-11-09');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('68121562207', 'Slawomir', 'Andrzejewski', '1968-12-15');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('28111615627', 'Jacek', 'Witkowski', '1928-11-16');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('98091667661', 'Monika', 'Jaworska', '1998-09-16');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('76080431071', 'Barbara', 'Jaworska', '1976-08-04');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('74120384294', 'Adam', 'Urbanski', '1974-12-03');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('45121746012', 'Jaroslaw', 'Michalski', '1945-12-17');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('70111382012', 'Marta', 'Kozlowska', '1970-11-13');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('71102374651', 'Waldemar', 'Kozlowski', '1971-10-23');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('95112080215', 'Iwona', 'Szymanska', '1995-11-20');
insert into Pacjent ("Pesel", "Imie", "Nazwisko", "Data_urodzenia") values ('21041931160', 'Sebastian', 'Kolodziej', '1921-04-19');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('1', '75110916195', '1999-05-12', '2000-07-09');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('2', '1081386371', '1999-10-20', '2000-10-07');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('3', '97042255430', '1998-04-29', '1998-11-16');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('4', '1081386371', '1994-08-08', '1996-11-22');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('5', '32032726668', '1991-09-26', '1999-03-17');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('6', '76080431071', '2000-12-18', '2000-12-29');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('7', '32032726668', '1991-03-16', '1998-11-18');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('8', '36050696173', '1993-12-15', '1997-10-25');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('9', '1081386371', '1996-12-14', '2000-07-22');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('10', '70111382012', '2000-04-05', '2000-10-11');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('11', '68121562207', '1999-11-14', '1999-11-29');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('12', '97042255430', '1996-03-24', '1997-12-17');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('13', '75110916195', '1994-07-02', '1998-07-20');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('14', '98091667661', '1998-06-26', '1999-02-14');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('15', '68121562207', '1994-03-16', '1994-09-17');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('16', '55021696928', '1995-10-08', '1996-07-28');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('17', '95112080215', '1999-03-06', '2000-07-01');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('18', '97042255430', '1997-05-28', '1998-12-20');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('19', '19062316521', '1994-04-15', '1999-09-05');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('20', '68121562207', '1998-07-22', '1998-12-29');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('21', '1081386371', '1992-07-09', '1998-03-21');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('22', '7102582372', '1992-05-08', '1996-11-16');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('23', '83030898247', '1992-09-15', '1996-07-21');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('24', '45121746012', '1990-12-26', '1998-02-16');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('25', '83030898247', '1992-02-17', '2000-05-31');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('26', '79061310141', '1996-05-30', '1997-03-01');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('27', '6101291052', '1993-10-12', '1998-08-26');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('28', '28111615627', '1997-08-31', '1997-09-20');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('29', '68121562207', '1992-04-11', '1994-08-29');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('30', '7102582372', '1997-02-05', '1999-04-27');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('31', '45121746012', '1998-06-30', '1998-10-16');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('32', '73012758111', '1998-07-22', '1999-07-04');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('33', '8060429910', '1991-04-02', '1996-09-04');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('34', '71102374651', '1991-09-18', '1996-10-15');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('35', '28111615627', '1994-03-31', '1997-03-17');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('36', '98091667661', '1997-08-27', '1999-10-18');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('37', '70111382012', '1993-11-06', '1994-09-18');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('38', '4011387894', '1993-08-24', '1993-09-08');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('39', '75110916195', '1993-10-01', '1993-10-27');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('40', '4011387894', '1999-12-17', '2000-05-26');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('41', '79061310141', '1996-01-12', '1999-02-19');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('42', '76080431071', '1994-07-03', '1997-03-07');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('43', '7102582372', '1994-11-11', '1998-05-10');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('44', '45121746012', '2000-02-17', '2000-06-28');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('45', '19062316521', '1990-11-09', '1999-06-18');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('46', '36050696173', '1993-10-30', '1995-07-19');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('47', '75110916195', '1992-12-05', '1996-06-14');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('48', '73012758111', '1997-02-09', '1997-09-01');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('49', '97042255430', '2000-05-12', '2000-06-20');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('50', '75110916195', '1994-07-03', '1999-01-03');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('51', '7102582372', '1991-04-15', '1999-09-21');
insert into Pobyt ("ID", "ID_pacjenta", "Data_przyjecia", "Data_wypisania") values ('52', '32032726668', '1992-12-24', '1997-10-14');
insert into Lek ("ID", "Nazwa") values ('1', '2 KC');
insert into Lek ("ID", "Nazwa") values ('2', '2 KC Xtreme');
insert into Lek ("ID", "Nazwa") values ('3', '2BeSlim');
insert into Lek ("ID", "Nazwa") values ('4', '4 Flex');
insert into Lek ("ID", "Nazwa") values ('5', '4 Flex Sport');
insert into Lek ("ID", "Nazwa") values ('6', '4 Flex Ultra');
insert into Lek ("ID", "Nazwa") values ('7', '4Lacti');
insert into Lek ("ID", "Nazwa") values ('8', 'Abacil');
insert into Lek ("ID", "Nazwa") values ('9', 'Abaktal');
insert into Lek ("ID", "Nazwa") values ('10', 'ABE');
insert into Lek ("ID", "Nazwa") values ('11', 'Abilify');
insert into Lek ("ID", "Nazwa") values ('12', 'Aripiprazolum');
insert into Lek ("ID", "Nazwa") values ('13', 'Abropernol N');
insert into Lek ("ID", "Nazwa") values ('14', 'Abrotanum Dagomed');
insert into Lek ("ID", "Nazwa") values ('15', 'Absenor');
insert into Lek ("ID", "Nazwa") values ('16', 'Natrii valproas');
insert into Lek ("ID", "Nazwa") values ('17', 'Abutol long 400');
insert into Lek ("ID", "Nazwa") values ('18', 'Acebutololum');
insert into Lek ("ID", "Nazwa") values ('19', 'Acai');
insert into Lek ("ID", "Nazwa") values ('20', 'Acard');
insert into Lek ("ID", "Nazwa") values ('21', 'Acard 150');
insert into Lek ("ID", "Nazwa") values ('22', 'Acidum');
insert into Lek ("ID", "Nazwa") values ('23', 'Acatar');
insert into Lek ("ID", "Nazwa") values ('24', 'Acatar Acti Tabs');
insert into Lek ("ID", "Nazwa") values ('25', 'Acatar Baby');
insert into Lek ("ID", "Nazwa") values ('26', 'Acatar Fast');
insert into Lek ("ID", "Nazwa") values ('27', 'Acatar Zatoki');
insert into Lek ("ID", "Nazwa") values ('28', 'Ibuprofenum');
insert into Lek ("ID", "Nazwa") values ('29', 'Acatarick Allergy');
insert into Lek ("ID", "Nazwa") values ('30', 'ACC');
insert into Lek ("ID", "Nazwa") values ('31', 'ACC Hot');
insert into Lek ("ID", "Nazwa") values ('32', 'ACC Max');
insert into Lek ("ID", "Nazwa") values ('33', 'ACC Mini');
insert into Lek ("ID", "Nazwa") values ('34', 'ACC optima');
insert into Lek ("ID", "Nazwa") values ('35', 'Accolate');
insert into Lek ("ID", "Nazwa") values ('36', 'Accupro');
insert into Lek ("ID", "Nazwa") values ('37', 'Accuzide');
insert into Lek ("ID", "Nazwa") values ('38', 'Acidolac');
insert into Lek ("ID", "Nazwa") values ('39', 'Acidolac Baby');
insert into Lek ("ID", "Nazwa") values ('40', 'Acidolac Junior');
insert into Lek ("ID", "Nazwa") values ('41', 'Acidolit');
insert into Lek ("ID", "Nazwa") values ('42', 'Adipobon mono');
insert into Lek ("ID", "Nazwa") values ('43', 'Adipobonisan');
insert into Lek ("ID", "Nazwa") values ('44', 'Aesculus compose');
insert into Lek ("ID", "Nazwa") values ('45', 'Aesculus compositum');
insert into Lek ("ID", "Nazwa") values ('46', 'Aesculus-Heel (krople)');
insert into Lek ("ID", "Nazwa") values ('47', 'Bactiflor');
insert into Lek ("ID", "Nazwa") values ('48', 'Bactilac SF');
insert into Lek ("ID", "Nazwa") values ('49', 'Bactum');
insert into Lek ("ID", "Nazwa") values ('50', 'Badiaga complexe Nr 47');
insert into Lek ("ID", "Nazwa") values ('51', 'Bakol Forte');
insert into Lek ("ID", "Nazwa") values ('52', 'Bakozin');
insert into Lek ("ID", "Nazwa") values ('53', 'Baktimax');
insert into Lek ("ID", "Nazwa") values ('54', 'Berberis Complexe Nr 83');
insert into Lek ("ID", "Nazwa") values ('55', 'Berberis-Homaccord (krople)');
insert into Lek ("ID", "Nazwa") values ('56', 'Beta Glukan (Walmark)');
insert into Lek ("ID", "Nazwa") values ('57', 'Beta Glukan 1,3/1,6D');
insert into Lek ("ID", "Nazwa") values ('58', 'Beta Glukan 10 Junior');
insert into Lek ("ID", "Nazwa") values ('59', 'Beta Glukan 50 (Virde)');
insert into Lek ("ID", "Nazwa") values ('60', 'Beta Glukan Farm 1,3 / 1,6 D');
insert into Lek ("ID", "Nazwa") values ('61', 'Beta Glukan Forte 100');
insert into Lek ("ID", "Nazwa") values ('62', 'Beta Glukan Multiwitamina');
insert into Lek ("ID", "Nazwa") values ('63', 'Beta Karot E Frot');
insert into Lek ("ID", "Nazwa") values ('64', 'Beta Karoten Naturkaps');
insert into Lek ("ID", "Nazwa") values ('65', 'Beta Karoten Sun');
insert into Lek ("ID", "Nazwa") values ('66', 'Beta Karowit');
insert into Lek ("ID", "Nazwa") values ('67', 'Beta Prostan');
insert into Lek ("ID", "Nazwa") values ('68', 'Beta-Sun-Bio');
insert into Lek ("ID", "Nazwa") values ('69', 'BioRelaxil');
insert into Lek ("ID", "Nazwa") values ('70', 'Bioretinof');
insert into Lek ("ID", "Nazwa") values ('71', 'Bioslank');
insert into Lek ("ID", "Nazwa") values ('72', 'Biotyk');
insert into Lek ("ID", "Nazwa") values ('73', 'Biotyk Complex');
insert into Lek ("ID", "Nazwa") values ('74', 'Biovilon');
insert into Lek ("ID", "Nazwa") values ('75', 'Biovital Multi Zelki dla doroslych');
insert into Lek ("ID", "Nazwa") values ('76', 'Biovital Pamiec');
insert into Lek ("ID", "Nazwa") values ('77', 'Biovital Zdrowie');
insert into Lek ("ID", "Nazwa") values ('78', 'Biovital Zdrowie z zen-szeniem');
insert into Lek ("ID", "Nazwa") values ('79', 'Biowap 1400');
insert into Lek ("ID", "Nazwa") values ('80', 'Biowap Chelat');
insert into Lek ("ID", "Nazwa") values ('81', 'Cactus compositum S (iniekcje)');
insert into Lek ("ID", "Nazwa") values ('82', 'Cactus Compositum S (krople)');
insert into Lek ("ID", "Nazwa") values ('83', 'Calcenato');
insert into Lek ("ID", "Nazwa") values ('84', 'Calci Strong+Magnez');
insert into Lek ("ID", "Nazwa") values ('85', 'Calcium C Forte Polfa-Lodz');
insert into Lek ("ID", "Nazwa") values ('86', 'Calcium C Rodzinna Apteczka');
insert into Lek ("ID", "Nazwa") values ('87', 'Calcium C+Zn');
insert into Lek ("ID", "Nazwa") values ('88', 'Calcoheel');
insert into Lek ("ID", "Nazwa") values ('89', 'Calcynovit 1250+D3');
insert into Lek ("ID", "Nazwa") values ('90', 'D Kidusie');
insert into Lek ("ID", "Nazwa") values ('91', 'D-Vitum');
insert into Lek ("ID", "Nazwa") values ('92', 'D-Vitum 800');
insert into Lek ("ID", "Nazwa") values ('93', 'D-Vitum Calcium');
insert into Lek ("ID", "Nazwa") values ('94', 'D-Vitum Forte 1000');
insert into Lek ("ID", "Nazwa") values ('95', 'D-Vitum Forte 2000');
insert into Lek ("ID", "Nazwa") values ('96', 'Diarrheel S');
insert into Lek ("ID", "Nazwa") values ('97', 'Diaton');
insert into Lek ("ID", "Nazwa") values ('98', 'Diaval Caps');
insert into Lek ("ID", "Nazwa") values ('99', 'Diaval Extra');
insert into Lek ("ID", "Nazwa") values ('100', 'Dida');
insert into Lek ("ID", "Nazwa") values ('101', 'Diet Guard');
insert into Lek ("ID", "Nazwa") values ('102', 'DietaVit');
insert into Lek ("ID", "Nazwa") values ('103', 'DietaVit Blonnik i Probiotyk');
insert into Lek ("ID", "Nazwa") values ('104', 'Espumisan Easy');
insert into Lek ("ID", "Nazwa") values ('105', 'Espumisan Kids');
insert into Lek ("ID", "Nazwa") values ('106', 'Espumisan MAX');
insert into Lek ("ID", "Nazwa") values ('107', 'Esselivecaps');
insert into Lek ("ID", "Nazwa") values ('108', 'Esselver');
insert into Lek ("ID", "Nazwa") values ('109', 'Essencicaps');
insert into Lek ("ID", "Nazwa") values ('110', 'Essensal Complex');
insert into Lek ("ID", "Nazwa") values ('111', 'Essetiamed');
insert into Lek ("ID", "Nazwa") values ('112', 'Essetil Complex');
insert into Lek ("ID", "Nazwa") values ('113', 'Essetrax');
insert into Lek ("ID", "Nazwa") values ('114', 'Essetreen complex');
insert into Lek ("ID", "Nazwa") values ('115', 'Falumax');
insert into Lek ("ID", "Nazwa") values ('116', 'Falvit');
insert into Lek ("ID", "Nazwa") values ('117', 'Falvit estro');
insert into Lek ("ID", "Nazwa") values ('118', 'Falvit Mama');
insert into Lek ("ID", "Nazwa") values ('119', 'Femal Forte Menopauza');
insert into Lek ("ID", "Nazwa") values ('120', 'Femal PMS Forte');
insert into Lek ("ID", "Nazwa") values ('121', 'Femaltiker');
insert into Lek ("ID", "Nazwa") values ('122', 'FemaPause (kapsulki)');
insert into Lek ("ID", "Nazwa") values ('123', 'Folic');
insert into Lek ("ID", "Nazwa") values ('124', 'Folic Active');
insert into Lek ("ID", "Nazwa") values ('125', 'Folicum acidum');
insert into Lek ("ID", "Nazwa") values ('126', 'Folidyne Protect');
insert into Lek ("ID", "Nazwa") values ('127', 'Galium-Heel N (iniekcje)');
insert into Lek ("ID", "Nazwa") values ('128', 'Galium-Heel N (krople)');
insert into Lek ("ID", "Nazwa") values ('129', 'Galomega');
insert into Lek ("ID", "Nazwa") values ('130', 'Galomega Formula IQ');
insert into Lek ("ID", "Nazwa") values ('131', 'Gardelix Junior');
insert into Lek ("ID", "Nazwa") values ('132', 'Gardimax (syrop)');
insert into Lek ("ID", "Nazwa") values ('133', 'Gardimax Junior');
insert into Lek ("ID", "Nazwa") values ('134', 'Gardimax Mini');
insert into Lek ("ID", "Nazwa") values ('135', 'Gardimax na Gardlo');
insert into Lek ("ID", "Nazwa") values ('136', 'Gardimax Termogripp');
insert into Lek ("ID", "Nazwa") values ('137', 'Gardloseptin');
insert into Lek ("ID", "Nazwa") values ('138', 'Gardlox (tabletki do ssania)');
insert into Lek ("ID", "Nazwa") values ('139', 'Gardlox 7 syrop ziolowy bez cukru');
insert into Lek ("ID", "Nazwa") values ('140', 'Gardlox Impact Forte');
insert into Lek ("ID", "Nazwa") values ('141', 'Ha-Pantoten Classic');
insert into Lek ("ID", "Nazwa") values ('142', 'Ha-Pantoten optimum');
insert into Lek ("ID", "Nazwa") values ('143', 'Hair Okey');
insert into Lek ("ID", "Nazwa") values ('144', 'Hairkare');
insert into Lek ("ID", "Nazwa") values ('145', 'Hamamelis-Homaccord');
insert into Lek ("ID", "Nazwa") values ('146', 'Hamamelis-Homaccord (iniekcje)');
insert into Lek ("ID", "Nazwa") values ('147', 'Happy Coffee');
insert into Lek ("ID", "Nazwa") values ('148', 'Happy Plus');
insert into Lek ("ID", "Nazwa") values ('149', 'Happy Tonic');
insert into Lek ("ID", "Nazwa") values ('150', 'Inneov Cellulit');
insert into Lek ("ID", "Nazwa") values ('151', 'Inneov D-Tox na niedoskonalosci');
insert into Lek ("ID", "Nazwa") values ('152', 'Inneov Drenaz');
insert into Lek ("ID", "Nazwa") values ('153', 'Inneov Gestosc wlosow');
insert into Lek ("ID", "Nazwa") values ('154', 'Inneov Gestosc wlosow - wlosy farbowane');
insert into Lek ("ID", "Nazwa") values ('155', 'Inneov Homme');
insert into Lek ("ID", "Nazwa") values ('156', 'Inneov Jedrnosc skory');
insert into Lek ("ID", "Nazwa") values ('157', 'Inneov Kuracja przeciw starzeniu');
insert into Lek ("ID", "Nazwa") values ('158', 'Inneov Slonce');
insert into Lek ("ID", "Nazwa") values ('159', 'Inneov Sucha Skora');
insert into Lek ("ID", "Nazwa") values ('160', 'Inofolic');
insert into Lek ("ID", "Nazwa") values ('161', 'Inozytol');
insert into Lek ("ID", "Nazwa") values ('162', 'Inseptox');
insert into Lek ("ID", "Nazwa") values ('163', 'Jeliton');
insert into Lek ("ID", "Nazwa") values ('164', 'Jelitowa Flora Bakteryjna');
insert into Lek ("ID", "Nazwa") values ('165', 'Jiao Gu Lan');
insert into Lek ("ID", "Nazwa") values ('166', 'Jod Activ');
insert into Lek ("ID", "Nazwa") values ('167', 'Junical D3');
insert into Lek ("ID", "Nazwa") values ('168', 'Junical Zeby');
insert into Lek ("ID", "Nazwa") values ('169', 'Junior angin');
insert into Lek ("ID", "Nazwa") values ('170', 'Juniperus Complexe Nr 6');
insert into Lek ("ID", "Nazwa") values ('171', 'Karczoch');
insert into Lek ("ID", "Nazwa") values ('172', 'KardioStabil');
insert into Lek ("ID", "Nazwa") values ('173', 'Karmelki Extra Starka');
insert into Lek ("ID", "Nazwa") values ('174', 'Karnifort');
insert into Lek ("ID", "Nazwa") values ('175', 'Karnityna Ambio');
insert into Lek ("ID", "Nazwa") values ('176', 'Karovit');
insert into Lek ("ID", "Nazwa") values ('177', 'L- Karnityna (Bio-Tech)');
insert into Lek ("ID", "Nazwa") values ('178', 'L- Karnityna (Herbapol)');
insert into Lek ("ID", "Nazwa") values ('179', 'L- Karnityna (Naturell)');
insert into Lek ("ID", "Nazwa") values ('180', 'L-Arginina');
insert into Lek ("ID", "Nazwa") values ('181', 'L-Karnityna 3 Activ Naturkaps');
insert into Lek ("ID", "Nazwa") values ('182', 'L-Karnityna 350');
insert into Lek ("ID", "Nazwa") values ('183', 'L-Karnityna 500 + chrom');
insert into Lek ("ID", "Nazwa") values ('184', 'L-Karnityna Direct');
insert into Lek ("ID", "Nazwa") values ('185', 'Sabal-Homaccord');
insert into Lek ("ID", "Nazwa") values ('186', 'Sabril');
insert into Lek ("ID", "Nazwa") values ('187', 'Sabumalin');
insert into Lek ("ID", "Nazwa") values ('188', 'Sachol');
insert into Lek ("ID", "Nazwa") values ('189', 'Sadamin');
insert into Lek ("ID", "Nazwa") values ('190', 'Salicylol');
insert into Lek ("ID", "Nazwa") values ('191', 'Sadamin prolongatum');
insert into Lek ("ID", "Nazwa") values ('192', 'Saflogin');
insert into Lek ("ID", "Nazwa") values ('193', 'Sal Carolinum Factitium effervescens');
insert into Lek ("ID", "Nazwa") values ('194', 'Sal Ems Artificiale');
insert into Lek ("ID", "Nazwa") values ('195', 'Sal Ems factitium');
insert into Lek ("ID", "Nazwa") values ('196', 'Sal Vichy Factitium');
insert into Lek ("ID", "Nazwa") values ('197', 'Salazopyrin EN');
insert into Lek ("ID", "Nazwa") values ('198', 'Salbutamolum');
insert into Lek ("ID", "Nazwa") values ('199', 'Salofalk');
insert into Lek ("ID", "Nazwa") values ('200', 'Saldiam');
insert into Lek ("ID", "Nazwa") values ('201', 'Salfazin');
insert into Lek ("ID", "Nazwa") values ('202', 'Salhydron');
insert into Lek ("ID", "Nazwa") values ('203', 'Salicis cortex extractum siccum');
insert into Lek ("ID", "Nazwa") values ('204', 'Salpirin');
insert into Lek ("ID", "Nazwa") values ('205', 'Salicortex');
insert into Lek ("ID", "Nazwa") values ('206', 'Salumin Activ');
insert into Lek ("ID", "Nazwa") values ('207', 'Saliderm');
insert into Lek ("ID", "Nazwa") values ('208', 'Saluran');
insert into Lek ("ID", "Nazwa") values ('209', 'Salipax');
insert into Lek ("ID", "Nazwa") values ('210', 'Salus Natura Calmagin');
insert into Lek ("ID", "Nazwa") values ('211', 'Salisal');
insert into Lek ("ID", "Nazwa") values ('212', 'Salivarex');
insert into Lek ("ID", "Nazwa") values ('213', 'Salix purpurea');
insert into Lek ("ID", "Nazwa") values ('214', 'Salmex');
insert into Lek ("ID", "Nazwa") values ('215', 'Salotannal');
insert into Lek ("ID", "Nazwa") values ('216', 'Salus Natura Beta glucan');
insert into Lek ("ID", "Nazwa") values ('217', 'Salus Natura Elagika');
insert into Lek ("ID", "Nazwa") values ('218', 'Salus Natura Femiflavon');
insert into Lek ("ID", "Nazwa") values ('219', 'Salus Natura G-Aktiv');
insert into Lek ("ID", "Nazwa") values ('220', 'Salus Natura Kwas Foliowy Plus');
insert into Lek ("ID", "Nazwa") values ('221', 'Sandimmun Neoral');
insert into Lek ("ID", "Nazwa") values ('222', 'Salus Natura Magnolia');
insert into Lek ("ID", "Nazwa") values ('223', 'Salus Natura ProKaroten');
insert into Lek ("ID", "Nazwa") values ('224', 'Salus Natura Superferrin');
insert into Lek ("ID", "Nazwa") values ('225', 'Salviae folii extracum');
insert into Lek ("ID", "Nazwa") values ('226', 'Octreotidum');
insert into Lek ("ID", "Nazwa") values ('227', 'Salviasept');
insert into Lek ("ID", "Nazwa") values ('228', 'Salvigol Bio Pediatric');
insert into Lek ("ID", "Nazwa") values ('229', 'Sampelo Kids');
insert into Lek ("ID", "Nazwa") values ('230', 'Sanostol');
insert into Lek ("ID", "Nazwa") values ('231', 'Sandoglobulin P');
insert into Lek ("ID", "Nazwa") values ('232', 'Sandostatin');
insert into Lek ("ID", "Nazwa") values ('233', 'SanoFerrin complex');
insert into Lek ("ID", "Nazwa") values ('234', 'Sanofil');
insert into Lek ("ID", "Nazwa") values ('235', 'Sanosvit Calcium');
insert into Lek ("ID", "Nazwa") values ('236', 'Olanzapinum');
insert into Lek ("ID", "Nazwa") values ('237', 'Sanprobi IBS');
insert into Lek ("ID", "Nazwa") values ('238', 'Sanza');
insert into Lek ("ID", "Nazwa") values ('239', 'Sapoven');
insert into Lek ("ID", "Nazwa") values ('240', 'Sapoven AT');
insert into Lek ("ID", "Nazwa") values ('241', 'Sapoven T');
insert into Lek ("ID", "Nazwa") values ('242', 'Saridon');
insert into Lek ("ID", "Nazwa") values ('243', 'Sarve');
insert into Lek ("ID", "Nazwa") values ('244', 'Satibo');
insert into Lek ("ID", "Nazwa") values ('245', 'Satinea');
insert into Lek ("ID", "Nazwa") values ('246', 'Satural');
insert into Lek ("ID", "Nazwa") values ('247', 'Savandra');
insert into Lek ("ID", "Nazwa") values ('248', 'Savarix');
insert into Lek ("ID", "Nazwa") values ('249', 'Saziadrink');
insert into Lek ("ID", "Nazwa") values ('250', 'S-Biotic');
insert into Lek ("ID", "Nazwa") values ('251', 'Scaldex');
insert into Lek ("ID", "Nazwa") values ('252', 'S-Cardiox');
insert into Lek ("ID", "Nazwa") values ('253', 'Schwef');
insert into Lek ("ID", "Nazwa") values ('254', 'Sclefic');
insert into Lek ("ID", "Nazwa") values ('255', 'Sclerocalcine');
insert into Lek ("ID", "Nazwa") values ('256', 'Scopolan');
insert into Lek ("ID", "Nazwa") values ('257', 'Sea Kelp');
insert into Lek ("ID", "Nazwa") values ('258', 'Amoxicillinum');
insert into Lek ("ID", "Nazwa") values ('259', 'Olanzapinum');
insert into Lek ("ID", "Nazwa") values ('260', 'Rami-A');
insert into Lek ("ID", "Nazwa") values ('261', 'Pantoprazolum');
insert into Lek ("ID", "Nazwa") values ('262', 'Ramicor');
insert into Lek ("ID", "Nazwa") values ('263', 'Ramiprilum');
insert into Lek ("ID", "Nazwa") values ('264', 'Radirex');
insert into Lek ("ID", "Nazwa") values ('265', 'Ramicor Comb');
insert into Lek ("ID", "Nazwa") values ('266', 'Ramipril Actavis');
insert into Lek ("ID", "Nazwa") values ('267', 'Ramipril Pfizer');
insert into Lek ("ID", "Nazwa") values ('268', 'Ramipril-ratiopharm');
insert into Lek ("ID", "Nazwa") values ('269', 'Ramiprilum 123ratio');
insert into Lek ("ID", "Nazwa") values ('270', 'Ramiprilum, Amlodipinum');
insert into Lek ("ID", "Nazwa") values ('271', 'Ramiprilum, Hydrochlorothiazidum');
insert into Lek ("ID", "Nazwa") values ('272', 'Ramistad');
insert into Lek ("ID", "Nazwa") values ('273', 'Ramizek');
insert into Lek ("ID", "Nazwa") values ('274', 'Ramoclav');
insert into Lek ("ID", "Nazwa") values ('275', 'Ranacand');
insert into Lek ("ID", "Nazwa") values ('276', 'Candesartanum cilexetilum');
insert into Lek ("ID", "Nazwa") values ('277', 'Ranexa');
insert into Lek ("ID", "Nazwa") values ('278', 'Ranolazinum');
insert into Lek ("ID", "Nazwa") values ('279', 'Raniberl');
insert into Lek ("ID", "Nazwa") values ('280', 'Ramve');
insert into Lek ("ID", "Nazwa") values ('281', 'Ranic (tabletki)');
insert into Lek ("ID", "Nazwa") values ('282', 'Ranigast');
insert into Lek ("ID", "Nazwa") values ('283', 'Ranigast Fast');
insert into Lek ("ID", "Nazwa") values ('284', 'Ranigast Max');
insert into Lek ("ID", "Nazwa") values ('285', 'Ranigast Pro');
insert into Lek ("ID", "Nazwa") values ('286', 'Ranimax');
insert into Lek ("ID", "Nazwa") values ('287', 'Ranisan 150');
insert into Lek ("ID", "Nazwa") values ('288', 'Ranitidinum');
insert into Lek ("ID", "Nazwa") values ('289', 'Ranisan 75');
insert into Lek ("ID", "Nazwa") values ('290', 'Ranitin');
insert into Lek ("ID", "Nazwa") values ('291', 'Ranitydyna');
insert into Lek ("ID", "Nazwa") values ('292', 'Ranloc');
insert into Lek ("ID", "Nazwa") values ('293', 'Ranlosin');
insert into Lek ("ID", "Nazwa") values ('294', 'Ranofren');
insert into Lek ("ID", "Nazwa") values ('295', 'Ranopril');
insert into Lek ("ID", "Nazwa") values ('296', 'Ubretid');
insert into Lek ("ID", "Nazwa") values ('297', 'Ulfamid');
insert into Lek ("ID", "Nazwa") values ('298', 'Ulgafen');
insert into Lek ("ID", "Nazwa") values ('299', 'Ulgamax');
insert into Lek ("ID", "Nazwa") values ('300', 'Ulgastran');
insert into Lek ("ID", "Nazwa") values ('301', 'Ulgix');
insert into Lek ("ID", "Nazwa") values ('302', 'Ultibro Breezhaler');
insert into Lek ("ID", "Nazwa") values ('303', 'Ultop');
insert into Lek ("ID", "Nazwa") values ('304', 'Ultracod');
insert into Lek ("ID", "Nazwa") values ('305', 'Ultrafastin');
insert into Lek ("ID", "Nazwa") values ('306', 'UltralaC');
insert into Lek ("ID", "Nazwa") values ('307', 'UltralaC Baby');
insert into Lek ("ID", "Nazwa") values ('308', 'UltralaC RICH');
insert into Lek ("ID", "Nazwa") values ('309', 'Ultratard HM');
insert into Lek ("ID", "Nazwa") values ('310', 'Ulzol');
insert into Lek ("ID", "Nazwa") values ('311', 'Unasyn');
insert into Lek ("ID", "Nazwa") values ('312', 'Undestor');
insert into Lek ("ID", "Nazwa") values ('313', 'Undofen');
insert into Lek ("ID", "Nazwa") values ('314', 'Uniben');
insert into Lek ("ID", "Nazwa") values ('315', 'UniCal 500D');
insert into Lek ("ID", "Nazwa") values ('316', 'Unidox Solutab');
insert into Lek ("ID", "Nazwa") values ('317', 'Unifungicid');
insert into Lek ("ID", "Nazwa") values ('318', 'UniKalk Basic');
insert into Lek ("ID", "Nazwa") values ('319', 'UniKalk Osteo');
insert into Choroba ("ID", "Nazwa") values ('1', 'Accne rosacea');
insert into Choroba ("ID", "Nazwa") values ('2', 'Achalazja');
insert into Choroba ("ID", "Nazwa") values ('3', 'Achondroplazja');
insert into Choroba ("ID", "Nazwa") values ('4', 'Acute lymphoblstic leukemia');
insert into Choroba ("ID", "Nazwa") values ('5', 'Acute myelogenous leukemia');
insert into Choroba ("ID", "Nazwa") values ('6', 'ADHD');
insert into Choroba ("ID", "Nazwa") values ('7', 'Afazja');
insert into Choroba ("ID", "Nazwa") values ('8', 'Afta');
insert into Choroba ("ID", "Nazwa") values ('9', 'Agnozja');
insert into Choroba ("ID", "Nazwa") values ('10', 'Agorafobia');
insert into Choroba ("ID", "Nazwa") values ('11', 'Agranulocytoza');
insert into Choroba ("ID", "Nazwa") values ('12', 'AIDS');
insert into Choroba ("ID", "Nazwa") values ('13', 'Akrofobia');
insert into Choroba ("ID", "Nazwa") values ('14', 'Akromegalia');
insert into Choroba ("ID", "Nazwa") values ('15', 'Aktynomikoza');
insert into Choroba ("ID", "Nazwa") values ('16', 'Albinizm');
insert into Choroba ("ID", "Nazwa") values ('17', 'Aldosteronizm');
insert into Choroba ("ID", "Nazwa") values ('18', 'Alergia');
insert into Choroba ("ID", "Nazwa") values ('19', 'Alergia atopowa');
insert into Choroba ("ID", "Nazwa") values ('20', 'Alergia kontaktowa');
insert into Choroba ("ID", "Nazwa") values ('21', 'Alergia krzyzowa');
insert into Choroba ("ID", "Nazwa") values ('22', 'Alergia na gluten');
insert into Choroba ("ID", "Nazwa") values ('23', 'Alergia na jad owadow');
insert into Choroba ("ID", "Nazwa") values ('24', 'Alergia na psa');
insert into Choroba ("ID", "Nazwa") values ('25', 'Alergia na roztocza');
insert into Choroba ("ID", "Nazwa") values ('26', 'Alergia pokarmowa');
insert into Choroba ("ID", "Nazwa") values ('27', 'Alergia wziewna');
insert into Choroba ("ID", "Nazwa") values ('28', 'Alergiczne kontaktowe zapalenie skory');
insert into Choroba ("ID", "Nazwa") values ('29', 'Alergiczne zapalenie pecherzykow plucnych');
insert into Choroba ("ID", "Nazwa") values ('30', 'Alergiczny katar');
insert into Choroba ("ID", "Nazwa") values ('31', 'Alergie skorne');
insert into Choroba ("ID", "Nazwa") values ('32', 'Alkoholizm');
insert into Choroba ("ID", "Nazwa") values ('33', 'Alkoholowe choroby watroby');
insert into Choroba ("ID", "Nazwa") values ('34', 'Alkoholowe zapalenie watroby');
insert into Choroba ("ID", "Nazwa") values ('35', 'Alkoholowy zespol abstynencyjny');
insert into Choroba ("ID", "Nazwa") values ('36', 'Amblyopia');
insert into Choroba ("ID", "Nazwa") values ('37', 'Ameboza');
insert into Choroba ("ID", "Nazwa") values ('38', 'Amyloidoza');
insert into Choroba ("ID", "Nazwa") values ('39', 'Anafilaksja');
insert into Choroba ("ID", "Nazwa") values ('40', 'Anaplazmoza');
insert into Choroba ("ID", "Nazwa") values ('41', 'Andropauza');
insert into Choroba ("ID", "Nazwa") values ('42', 'Anemia');
insert into Choroba ("ID", "Nazwa") values ('43', 'Anemia aplastyczna');
insert into Choroba ("ID", "Nazwa") values ('44', 'Anemia gornikow');
insert into Choroba ("ID", "Nazwa") values ('45', 'Anemia sierpowata');
insert into Choroba ("ID", "Nazwa") values ('46', 'Angina');
insert into Choroba ("ID", "Nazwa") values ('47', 'Angina brzuszna');
insert into Choroba ("ID", "Nazwa") values ('48', 'Angina monocytowa');
insert into Choroba ("ID", "Nazwa") values ('49', 'Angina ropna');
insert into Choroba ("ID", "Nazwa") values ('50', 'Anhedonia');
insert into Choroba ("ID", "Nazwa") values ('51', 'Anisakioza');
insert into Choroba ("ID", "Nazwa") values ('52', 'Ankylostymoza');
insert into Choroba ("ID", "Nazwa") values ('53', 'Anomalia Pelgera - Hueta');
insert into Choroba ("ID", "Nazwa") values ('54', 'Anoreksja');
insert into Choroba ("ID", "Nazwa") values ('55', 'Anorgazmia');
insert into Choroba ("ID", "Nazwa") values ('56', 'Anosmia');
insert into Choroba ("ID", "Nazwa") values ('57', 'Anxiety neurosis');
insert into Choroba ("ID", "Nazwa") values ('58', 'Apophysitis calcanei');
insert into Choroba ("ID", "Nazwa") values ('59', 'Artretyzm');
insert into Choroba ("ID", "Nazwa") values ('60', 'Artroza');
insert into Choroba ("ID", "Nazwa") values ('61', 'Artroza kregoslupowo-zebrowa');
insert into Choroba ("ID", "Nazwa") values ('62', 'Artroza segmentu kregowego');
insert into Choroba ("ID", "Nazwa") values ('63', 'Arytmia');
insert into Choroba ("ID", "Nazwa") values ('64', 'Askarioza');
insert into Choroba ("ID", "Nazwa") values ('65', 'Aspergiloza');
insert into Choroba ("ID", "Nazwa") values ('66', 'Astma aspirynowa');
insert into Choroba ("ID", "Nazwa") values ('67', 'Astma kaszlowa');
insert into Choroba ("ID", "Nazwa") values ('68', 'Astma oskrzelowa');
insert into Choroba ("ID", "Nazwa") values ('69', 'Astma pylkowa');
insert into Choroba ("ID", "Nazwa") values ('70', 'Astma sercowa');
insert into Choroba ("ID", "Nazwa") values ('71', 'Astma wysilkowa');
insert into Choroba ("ID", "Nazwa") values ('72', 'Astygmatyzm');
insert into Choroba ("ID", "Nazwa") values ('73', 'Ataksja rdzeniowo - mozdzkowa');
insert into Choroba ("ID", "Nazwa") values ('74', 'Athaeroma');
insert into Choroba ("ID", "Nazwa") values ('75', 'Atopowe zapalenie skory');
insert into Choroba ("ID", "Nazwa") values ('76', 'Atopowe zapalenie spojowek i rogowki');
insert into Choroba ("ID", "Nazwa") values ('77', 'Autoimmunologiczne zapalenie watroby');
insert into Choroba ("ID", "Nazwa") values ('78', 'Autyzm');
insert into Choroba ("ID", "Nazwa") values ('79', 'Azbestoza');
insert into Choroba ("ID", "Nazwa") values ('80', 'Babejoza');
insert into Choroba ("ID", "Nazwa") values ('81', 'Bakteryjne zapalenie pochwy');
insert into Choroba ("ID", "Nazwa") values ('82', 'Bakteryjne zapalenie wsierdzia');
insert into Choroba ("ID", "Nazwa") values ('83', 'Balantidioza');
insert into Choroba ("ID", "Nazwa") values ('84', 'Bartoneloza');
insert into Choroba ("ID", "Nazwa") values ('85', 'Bablowica');
insert into Choroba ("ID", "Nazwa") values ('86', 'Bezmocz mechaniczny');
insert into Choroba ("ID", "Nazwa") values ('87', 'Bezsennosc');
insert into Choroba ("ID", "Nazwa") values ('88', 'Bebnica');
insert into Choroba ("ID", "Nazwa") values ('89', 'Bialaczka');
insert into Choroba ("ID", "Nazwa") values ('90', 'Bialaczka wlochatokomorkowa');
insert into Choroba ("ID", "Nazwa") values ('91', 'Biegunka');
insert into Choroba ("ID", "Nazwa") values ('92', 'Biegunka podroznych');
insert into Choroba ("ID", "Nazwa") values ('93', 'Biegunka rotawirusowa');
insert into Choroba ("ID", "Nazwa") values ('94', 'Bielactwo nabyte');
insert into Choroba ("ID", "Nazwa") values ('95', 'Biodro przeskakujace');
insert into Choroba ("ID", "Nazwa") values ('96', 'Bladosc');
insert into Choroba ("ID", "Nazwa") values ('97', 'Blastomykoza');
insert into Choroba ("ID", "Nazwa") values ('98', 'Bledne kolo');
insert into Choroba ("ID", "Nazwa") values ('99', 'Blonica');
insert into Choroba ("ID", "Nazwa") values ('100', 'Celiakia');
insert into Choroba ("ID", "Nazwa") values ('101', 'Chlamydia i ureaplazma');
insert into Choroba ("ID", "Nazwa") values ('102', 'Chlamydioza');
insert into Choroba ("ID", "Nazwa") values ('103', 'Chloniak Burkitta');
insert into Choroba ("ID", "Nazwa") values ('104', 'Chloniak grudkowy');
insert into Choroba ("ID", "Nazwa") values ('105', 'Chloniak MALT');
insert into Choroba ("ID", "Nazwa") values ('106', 'Chloniak zoladka');
insert into Choroba ("ID", "Nazwa") values ('107', 'Chloniaki');
insert into Choroba ("ID", "Nazwa") values ('108', 'Chloniaki zoladka');
insert into Choroba ("ID", "Nazwa") values ('109', 'Cholera');
insert into Choroba ("ID", "Nazwa") values ('110', 'Cholestaza ciezarnych');
insert into Choroba ("ID", "Nazwa") values ('111', 'Chondromalacja rzepki');
insert into Choroba ("ID", "Nazwa") values ('112', 'Choroba afektywna');
insert into Choroba ("ID", "Nazwa") values ('113', 'Choroba Alzheimera');
insert into Choroba ("ID", "Nazwa") values ('114', 'Choroba Banga');
insert into Choroba ("ID", "Nazwa") values ('115', 'Choroba Bechterewa');
insert into Choroba ("ID", "Nazwa") values ('116', 'Choroba Buergera');
insert into Choroba ("ID", "Nazwa") values ('117', 'Choroba Burgera');
insert into Choroba ("ID", "Nazwa") values ('118', 'Choroba Chagasa');
insert into Choroba ("ID", "Nazwa") values ('119', 'Choroba Cushinga');
insert into Choroba ("ID", "Nazwa") values ('120', 'Choroba Dariera');
insert into Choroba ("ID", "Nazwa") values ('121', 'Choroba de Quervainea');
insert into Choroba ("ID", "Nazwa") values ('122', 'Choroba dekompresyjna');
insert into Choroba ("ID", "Nazwa") values ('123', 'Choroba Dercuma');
insert into Choroba ("ID", "Nazwa") values ('124', 'Choroba Duplaya');
insert into Choroba ("ID", "Nazwa") values ('125', 'Dalekowzrocznosc');
insert into Choroba ("ID", "Nazwa") values ('126', 'Daltonizm');
insert into Choroba ("ID", "Nazwa") values ('127', 'Demencja pourazowa');
insert into Choroba ("ID", "Nazwa") values ('128', 'Depresja');
insert into Choroba ("ID", "Nazwa") values ('129', 'Depresja poporodowa');
insert into Choroba ("ID", "Nazwa") values ('130', 'Depresja zimowa');
insert into Choroba ("ID", "Nazwa") values ('131', 'Difteria');
insert into Choroba ("ID", "Nazwa") values ('132', 'Difylobotrioza');
insert into Choroba ("ID", "Nazwa") values ('133', 'Dna moczanowa');
insert into Choroba ("ID", "Nazwa") values ('134', 'Drakunkuloza');
insert into Choroba ("ID", "Nazwa") values ('135', 'Dreszcze');
insert into Choroba ("ID", "Nazwa") values ('136', 'Drgawki');
insert into Choroba ("ID", "Nazwa") values ('137', 'Drozdzyca');
insert into Choroba ("ID", "Nazwa") values ('138', 'Drzaczka porazna');
insert into Choroba ("ID", "Nazwa") values ('139', 'Drzenie klatki piersiowej - mruki');
insert into Choroba ("ID", "Nazwa") values ('140', 'Drzenie rak');
insert into Choroba ("ID", "Nazwa") values ('141', 'Dur brzuszny');
insert into Choroba ("ID", "Nazwa") values ('142', 'Dur plamisty');
insert into Choroba ("ID", "Nazwa") values ('143', 'Jadlowstret psychiczny');
insert into Choroba ("ID", "Nazwa") values ('144', 'Jaglica');
insert into Choroba ("ID", "Nazwa") values ('145', 'Jalowa martwica kosci');
insert into Choroba ("ID", "Nazwa") values ('146', 'Jaskra');
insert into Choroba ("ID", "Nazwa") values ('147', 'Jaskra dziecieca (wrodzona)');
insert into Choroba ("ID", "Nazwa") values ('148', 'Jaskra u dzieci');
insert into Choroba ("ID", "Nazwa") values ('149', 'Jadrzak');
insert into Choroba ("ID", "Nazwa") values ('150', 'Jakanie u dziecka');
insert into Choroba ("ID", "Nazwa") values ('151', 'Jersinioza');
insert into Choroba ("ID", "Nazwa") values ('152', 'Jeczmien');
insert into Choroba ("ID", "Nazwa") values ('153', 'Gruzlica');
insert into Choroba ("ID", "Nazwa") values ('154', 'Gruzlica kostno-stawowa');
insert into Choroba ("ID", "Nazwa") values ('155', 'Gruzlica narzadu rodnego');
insert into Choroba ("ID", "Nazwa") values ('156', 'Gruzlica pluc');
insert into Choroba ("ID", "Nazwa") values ('157', 'Gruzlica urologiczna');
insert into Choroba ("ID", "Nazwa") values ('158', 'Grypa');
insert into Choroba ("ID", "Nazwa") values ('159', 'Grypa zoladkowa: grypa jelitowa - jelitowka');
insert into Choroba ("ID", "Nazwa") values ('160', 'Grzybica dloni');
insert into Choroba ("ID", "Nazwa") values ('161', 'Grzybica jezyka');
insert into Choroba ("ID", "Nazwa") values ('162', 'Grzybica pachwin');
insert into Choroba ("ID", "Nazwa") values ('163', 'Grzybica paznokci');
insert into Choroba ("ID", "Nazwa") values ('164', 'Grzybica pluc');
insert into Choroba ("ID", "Nazwa") values ('165', 'Grzybica pochwy');
insert into Choroba ("ID", "Nazwa") values ('166', 'Nadcisnienie naczyniowonerkowe');
insert into Choroba ("ID", "Nazwa") values ('167', 'Nadcisnienie tetnicze');
insert into Choroba ("ID", "Nazwa") values ('168', 'Nadczynnosc gruczolow przytarczycznych');
insert into Choroba ("ID", "Nazwa") values ('169', 'Nadczynnosc hormonalna jader');
insert into Choroba ("ID", "Nazwa") values ('170', 'Nadczynnosc przytarczyc');
insert into Choroba ("ID", "Nazwa") values ('171', 'Nadczynnosc tarczycy');
insert into Choroba ("ID", "Nazwa") values ('172', 'Nadkrwistosc');
insert into Choroba ("ID", "Nazwa") values ('173', 'Nadmierne krwawienia miesieczne');
insert into Choroba ("ID", "Nazwa") values ('174', 'Nadmierne lzawienie');
insert into Choroba ("ID", "Nazwa") values ('175', 'Nadmierne owlosienie');
insert into Choroba ("ID", "Nazwa") values ('176', 'Nadmierne pragnienie');
insert into Choroba ("ID", "Nazwa") values ('177', 'Nadwrazliwosc pokarmowa');
insert into Choroba ("ID", "Nazwa") values ('178', 'Nadwrazliwosc zebiny');
insert into Choroba ("ID", "Nazwa") values ('179', 'Nadwrazliwosc zebow');
insert into Choroba ("ID", "Nazwa") values ('180', 'Nadwzrocznosc');
insert into Choroba ("ID", "Nazwa") values ('181', 'Nadzerka szyjki macicy');
insert into Choroba ("ID", "Nazwa") values ('182', 'Nagla gluchota');
insert into Choroba ("ID", "Nazwa") values ('183', 'Nagminne zapalenie przyusznic');
insert into Choroba ("ID", "Nazwa") values ('184', 'Napadowa hemoglobinuria z zimna');
insert into Choroba ("ID", "Nazwa") values ('185', 'Napady hipoksemiczne');
insert into Choroba ("ID", "Nazwa") values ('186', 'Narkolepsja');
insert into Choroba ("ID", "Nazwa") values ('187', 'Ucho plywaka');
insert into Choroba ("ID", "Nazwa") values ('188', 'Uchylek Meckela');
insert into Choroba ("ID", "Nazwa") values ('189', 'Uczulenie');
insert into Choroba ("ID", "Nazwa") values ('190', 'Udar mozgu');
insert into Choroba ("ID", "Nazwa") values ('191', 'Ukladowe zapalenia naczyn');
insert into Choroba ("ID", "Nazwa") values ('192', 'Uposledzenie umyslowe');
insert into Choroba ("ID", "Nazwa") values ('193', 'Uraz akustyczny');
insert into Choroba ("ID", "Nazwa") values ('194', 'Urazy glowy');
insert into Choroba ("ID", "Nazwa") values ('195', 'Urazy i zlamania nosa');
insert into Choroba ("ID", "Nazwa") values ('196', 'Uremia');
insert into Choroba ("ID", "Nazwa") values ('197', 'Uszkodzenie nerwow obwodowych');
insert into Choroba ("ID", "Nazwa") values ('198', 'Uszkodzenie oka energia promienista');
insert into Choroba ("ID", "Nazwa") values ('199', 'Zaburzenia afektywne');
insert into Choroba ("ID", "Nazwa") values ('200', 'Zaburzenia czucia');
insert into Choroba ("ID", "Nazwa") values ('201', 'Zaburzenia czynnosci wewnatrzwydzielniczej jajnikow');
insert into Choroba ("ID", "Nazwa") values ('202', 'Zaburzenia krzepniecia krwi');
insert into Choroba ("ID", "Nazwa") values ('203', 'Zaburzenia nerwicowe');
insert into Choroba ("ID", "Nazwa") values ('204', 'Zaburzenia obsesyjno-kompulsywne');
insert into Choroba ("ID", "Nazwa") values ('205', 'Zaburzenia osobowosci');
insert into Choroba ("ID", "Nazwa") values ('206', 'Zaburzenia pamieci i intelektu');
insert into Choroba ("ID", "Nazwa") values ('207', 'Zaburzenia percepcji wzrokowej');
insert into Choroba ("ID", "Nazwa") values ('208', 'Zaburzenia psychiczne');
insert into Choroba ("ID", "Nazwa") values ('209', 'Zaburzenia rownowagi');
insert into Choroba ("ID", "Nazwa") values ('210', 'Zaburzenia w oddawaniu moczu');
insert into Choroba ("ID", "Nazwa") values ('211', 'Zaburzenie rytmu serca');
insert into Choroba ("ID", "Nazwa") values ('212', 'Zacma');
insert into Choroba ("ID", "Nazwa") values ('213', 'Zacma dziecieca');
insert into Choroba ("ID", "Nazwa") values ('214', 'Zacma starcza');
insert into Choroba ("ID", "Nazwa") values ('215', 'Zakazenia adenowirusami');
insert into Choroba ("ID", "Nazwa") values ('216', 'Zakazenia ukladu moczowego');
insert into Choroba ("ID", "Nazwa") values ('217', 'Zakazenie gronkowcem zlocistym');
insert into Choroba ("ID", "Nazwa") values ('218', 'Zakazenie laseczka jadu kielbasianego');
insert into Choroba ("ID", "Nazwa") values ('219', 'Zakazenie meningokokami');
insert into Choroba ("ID", "Nazwa") values ('220', 'Zakazenie osrodkowego ukladu nerwowego');
insert into Choroba ("ID", "Nazwa") values ('221', 'Zakazenie paciorkowcem');
insert into Choroba ("ID", "Nazwa") values ('222', 'Zakazenie pneumokokami');
insert into Choroba ("ID", "Nazwa") values ('223', 'Zakazenie pologowe');
insert into Choroba ("ID", "Nazwa") values ('224', 'Zakazenie poronne');
insert into Choroba ("ID", "Nazwa") values ('225', 'Zakazenie rotawirusem');
insert into Choroba ("ID", "Nazwa") values ('226', 'Zakazenie rzesistkiem pochwowym');
insert into Choroba ("ID", "Nazwa") values ('227', 'Zakazenie wirusem Coxsackie');
insert into Choroba ("ID", "Nazwa") values ('228', 'Zakazenie wirusem Ebola');
insert into Choroba ("ID", "Nazwa") values ('229', 'Zakazenie wirusem opryszczki zwyklej');
insert into Choroba ("ID", "Nazwa") values ('230', 'Zakleszczajace zapalenie sciegna');
insert into Choroba ("ID", "Nazwa") values ('231', 'Zakrzepica zyl glebokich konczyn dolnych');
insert into Choroba ("ID", "Nazwa") values ('232', 'Zakrzepowa plamica maloplytkowa');
insert into Choroba ("ID", "Nazwa") values ('233', 'Zakrzepowe zapalenie zyl');
insert into Choroba ("ID", "Nazwa") values ('234', 'Zakrzepowo-zarostowe zapalenie tetnic i zyl');
insert into Choroba ("ID", "Nazwa") values ('235', 'Zakupoholizm');
insert into Choroba ("ID", "Nazwa") values ('236', 'Zakwaszenie organizmu');
insert into Choroba ("ID", "Nazwa") values ('237', 'Zanokcica');
insert into Choroba ("ID", "Nazwa") values ('238', 'Zapalenia drog oddechowych');
insert into Choroba ("ID", "Nazwa") values ('239', 'Zapalenia twardowki');
insert into Choroba ("ID", "Nazwa") values ('240', 'Zapalenie blednika');
insert into Choroba ("ID", "Nazwa") values ('241', 'Zapalenie blony sluzowej nosa');
insert into Choroba ("ID", "Nazwa") values ('242', 'Zapalenie blony sluzowej zoladka');
insert into Choroba ("ID", "Nazwa") values ('243', 'Zapalenie brzegow powiek');
insert into Choroba ("ID", "Nazwa") values ('244', 'Zapalenie cewki moczowej');
insert into Choroba ("ID", "Nazwa") values ('245', 'Zapalenie cewki moczowej u mezczyzn');
insert into Choroba ("ID", "Nazwa") values ('246', 'Zapalenie drog moczowych');
insert into Choroba ("ID", "Nazwa") values ('247', 'Zapalenie drog zolciowych');
insert into Choroba ("ID", "Nazwa") values ('248', 'Zapalenie dziasel');
insert into Choroba ("ID", "Nazwa") values ('249', 'Zapalenie gardla');
insert into Choroba ("ID", "Nazwa") values ('250', 'Zapalenie gesiej stopy');
