insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('1', 'Sebastian', 'Ziolkowski', 'Kardiologia', '1991-01-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('2', 'Jan', 'Stepien', 'Audiologia i foniatria', '2000-08-30', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('3', 'Slawomir', 'Chmielewski', 'Zdrowie Publiczne', '1990-07-03', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('4', 'Jadwiga', 'Jankowska', 'Patomorfologia', '2000-05-04', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('5', 'Anna', 'Dudek', 'Urologia', '1995-10-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('6', 'Mateusz', 'Ostrowski', 'Pediatria', '1995-06-21', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('7', 'Dariusz', 'Witkowski', 'Chirurgia ogolna', '1996-06-06', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('8', 'Joanna', 'Wilk', 'Psychiatria dzieci i mlodziezy', '1997-12-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('9', 'Karol', 'Majewski', 'Radioterapia onkologiczna', '1992-03-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('10', 'Roman', 'Dudek', 'Audiologia i foniatria', '1996-01-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('11', 'Dariusz', 'Ziolkowski', 'Choroby wewnetrzne', '1990-12-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('12', 'Przemyslaw', 'Majewski', 'Diagnostyka laboratoryjna', '1998-04-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('13', 'Karolina', 'Szymczak', 'Dermatologia i wenerologia', '1993-01-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('14', 'Mateusz', 'Wysocki', 'Psychiatria dzieci i mlodziezy', '2000-12-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('15', 'Sebastian', 'Wisniewski', 'Psychiatria dzieci i mlodziezy', '1999-01-25', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('16', 'Teresa', 'Mazurek', 'Chirurgia ogolna', '1992-11-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('17', 'Edyta', 'Mazurek', 'Mikrobiologia lekarska', '1997-07-07', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('18', 'Jadwiga', 'Kaminska', 'Dermatologia i wenerologia', '1991-02-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('19', 'Sylwia', 'Kucharska', 'Medycyna ratunkowa', '2000-12-11', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('20', 'Adam', 'Kubiak', 'Psychiatria', '1991-03-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('21', 'Janusz', 'Wisniewski', 'Dermatologia i wenerologia', '1992-10-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('22', 'Jadwiga', 'Glowacka', 'Neonatologia', '1997-03-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('23', 'Grazyna', 'Tomaszewska', 'Onkologia kliniczna', '1997-03-03', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('24', 'Jacek', 'Kozlowski', 'Okulistyka', '1994-12-28', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('25', 'Henryk', 'Glowacki', 'Radiologia i diagnostyka obrazowa', '1997-10-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('26', 'Jan', 'Sikorski', 'Otorynolaryngologia', '1991-07-11', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('27', 'Sebastian', 'Nowakowski', 'Radioterapia onkologiczna', '1990-01-25', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('28', 'Stanislawa', 'Brzezinska', 'Onkologia kliniczna', '1991-03-28', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('29', 'Katarzyna', 'Witkowska', 'Onkologia kliniczna', '1996-11-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('30', 'Monika', 'Kucharska', 'Patomorfologia', '1999-03-25', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('31', 'Mateusz', 'Baranowski', 'Patomorfologia', '1991-06-12', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('32', 'Marek', 'Przybylski', 'Urologia', '1996-03-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('33', 'Bozena', 'Wozniak', 'Anestezjologia i intensywna terapia', '1994-04-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('34', 'Aleksandra', 'Kalinowska', 'Medycyna transportu', '1996-12-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('35', 'Daniel', 'Krol', 'Kardiochirurgia', '1998-03-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('36', 'Slawomir', 'Andrzejewski', 'Anestezjologia i intensywna terapia', '1994-02-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('37', 'Anna', 'Krawczyk', 'Psychiatria', '1994-08-20', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('38', 'Danuta', 'Maciejewska', 'Radioterapia onkologiczna', '1992-10-26', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('39', 'Jacek', 'Kozlowski', 'Neonatologia', '1995-06-02', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('40', 'Genowefa', 'Majewska', 'Epidemiologia', '1990-07-18', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('41', 'Mariusz', 'Kucharski', 'Audiologia i foniatria', '1999-02-15', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('42', 'Wojciech', 'Rutkowski', 'Radiologia i diagnostyka obrazowa', '1997-07-14', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('43', 'Stefania', 'Zajac', 'Pediatria', '1998-12-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('44', 'Przemyslaw', 'Gorski', 'Chirurgia ogolna', '2000-05-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('45', 'Jaroslaw', 'Nowak', 'Psychiatria dzieci i mlodziezy', '1996-08-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('46', 'Janina', 'Lewandowska', 'Urologia', '2000-09-07', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('47', 'Aleksandra', 'Wroblewska', 'Chirurgia szczekowo-twarzowa', '1990-05-08', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('48', 'Anna', 'Nowakowska', 'Chirurgia plastyczna', '1998-06-28', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('49', 'Dorota', 'Bak', 'Otorynolaryngologia', '1998-08-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('50', 'Henryk', 'Sawicki', 'Otorynolaryngologia', '1993-06-26', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('51', 'Ewelina', 'Szymczak', 'Mikrobiologia lekarska', '1998-01-04', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('52', 'Barbara', 'Walczak', 'Urologia', '2009-12-16', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('53', 'Ewa', 'Jakubowska', 'Medycyna transportu', '2008-08-22', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('54', 'Tadeusz', 'Kazmierczak', 'Chirurgia dziecieca', '2007-09-05', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('55', 'Tomasz', 'Andrzejewski', 'Kardiochirurgia', '2002-01-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('56', 'Leszek', 'Lis', 'Medycyna pracy', '2005-07-17', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('57', 'Marta', 'Dabrowska', 'Chirurgia klatki piersiowej', '2005-08-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('58', 'Marzena', 'Kolodziej', 'Medycyna sadowa', '2000-08-04', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('59', 'Pawel', 'Gorski', 'Choroby zakazne', '2005-04-26', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('60', 'Zdzislaw', 'Wrobel', 'Onkologia kliniczna', '2003-09-06', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('61', 'Lukasz', 'Kaminski', 'Kardiologia', '2002-11-07', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('62', 'Mariusz', 'Wlodarczyk', 'Mikrobiologia lekarska', '2000-10-31', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('63', 'Joanna', 'Zalewska', 'Chirurgia ogolna', '2005-04-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('64', 'Jolanta', 'Krol', 'Rehabilitacja medyczna', '2003-05-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('65', 'Pawel', 'Kaminski', 'Rehabilitacja medyczna', '2009-02-02', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('66', 'Przemyslaw', 'Dudek', 'Onkologia kliniczna', '2005-07-06', '2008-05-28')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('67', 'Izabela', 'Wlodarczyk', 'Patomorfologia', '2000-01-24', '2001-03-10')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('68', 'Halina', 'Mazurek', 'Neurochirurgia', '2006-01-13', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('69', 'Czeslaw', 'Cieslak', 'Pediatria', '2000-05-03', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('70', 'Patrycja', 'Nowicka', 'Chirurgia plastyczna', '2009-03-13', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('71', 'Jolanta', 'Tomaszewska', 'Medycyna rodzinna', '2006-10-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('72', 'Ewa', 'Baran', 'Kardiochirurgia', '2001-01-02', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('73', 'Jacek', 'Pietrzak', 'Medycyna ratunkowa', '2004-05-13', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('74', 'Elzbieta', 'Baranowska', 'Radiologia i diagnostyka obrazowa', '2003-11-21', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('75', 'Dariusz', 'Kwiatkowski', 'Chirurgia szczekowo-twarzowa', '2004-12-16', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('76', 'Karolina', 'Baran', 'Urologia', '2001-11-09', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('77', 'Wojciech', 'Laskowski', 'Neurologia', '2001-10-06', '2001-10-31')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('78', 'Karol', 'Mazurek', 'Ortopedia i traumatologia narzadu ruchu', '2004-03-03', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('79', 'Mateusz', 'Lewandowski', 'Genetyka kliniczna', '2003-12-08', '2008-10-06')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('80', 'Daniel', 'Wisniewski', 'Genetyka kliniczna', '2001-07-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('81', 'Pawel', 'Kozlowski', 'Chirurgia plastyczna', '2002-03-09', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('82', 'Grazyna', 'Mazurek', 'Medycyna rodzinna', '2005-09-04', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('83', 'Waldemar', 'Lewandowski', 'Anestezjologia i intensywna terapia', '2002-01-11', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('84', 'Karolina', 'Kaczmarek', 'Pediatria', '2000-08-08', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('85', 'Jacek', 'Jankowski', 'Medycyna nuklearna', '2000-06-30', '2009-06-04')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('86', 'Wieslaw', 'Kozlowski', 'Chirurgia dziecieca', '2010-05-12', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('87', 'Anna', 'Sikorska', 'Audiologia i foniatria', '2000-05-21', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('88', 'Katarzyna', 'Majewska', 'Chirurgia ogolna', '2009-06-26', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('89', 'Michal', 'Ostrowski', 'Neurochirurgia', '2005-09-20', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('90', 'Marzena', 'Wlodarczyk', 'Medycyna transportu', '2008-07-06', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('91', 'Dorota', 'Wrobel', 'Urologia', '2007-11-10', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('92', 'Mariusz', 'Glowacki', 'Otorynolaryngologia', '2006-05-01', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('93', 'Bozena', 'Nowak', 'Medycyna ratunkowa', '2001-07-19', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('94', 'Katarzyna', 'Wisniewska', 'Onkologia kliniczna', '2001-09-21', '2007-01-03')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('95', 'Tomasz', 'Czerwinski', 'Radioterapia onkologiczna', '2008-10-11', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('96', 'Wieslawa', 'Szewczyk', 'Zdrowie Publiczne', '2001-02-09', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('97', 'Kazimiera', 'Pietrzak', 'Medycyna nuklearna', '2003-02-24', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('98', 'Agnieszka', 'Czarnecka', 'Radiologia i diagnostyka obrazowa', '2002-11-18', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('99', 'Helena', 'Jaworska', 'Kardiologia', '2004-06-27', 'null')
insert into Lekarz ("ID", "Imie", "Nazwisko", "Specjalizacja", "Data zatrudnienia", "Data zwolnienia") values ('100', 'Zdzislaw', 'Nowak', 'Psychiatria', '2005-05-19', '2009-11-12')
